### ISSUE TITLE
Lifecycle Method for API Call

### ISSUE THREAD

**Issue by richardzeng1** [siefkenj/ta-toy#4]
Since `beforeRouteEnter` is as router lifecycle method that is called before the new route is entered, this requires the `next()` function to be called to persist data through to the next link. This produces difficult to understand code. 

Instead use the mounted lifecycle method.
```
mounted(){
        fetch("../get_info.php?course=" + this.$route.params.course)
            .then(response => {
                return response.json();
            })
            .then(data => {
                this.TAs = data.DATA;
            })
            .catch(error => {
                console.log(error);
            });
        console.log(TAs);
    },
```

If you've used React, this function is similar to `componentDidMount()`. Please make these changes to your code. @F-Ting

**Comment by DarrenZhang01** [comment]
Thanks, I will think about this one

**Comment by richardzeng1** [comment]
@DarrenZhang01  @F-Ting 
My mistake. After doing additional reading, I found that `created()` is the optimal lifecycle method to use for API calls. This function is called when the instance has been created but not yet mounted. Within this function, we have access to the reactive data but no access to the DOM. 

From what I've seen online, it is good practice to use `created()`.

**Comment by richardzeng1** [comment]
6383129097689f34df65bea86480e5d670e38fb2

**Comment by richardzeng1** [comment]
bcbd294e47dd368380da8cb22bbc437fec33a14e
